name: Release
on:
  release:
    types:
      - released

jobs:
  build:
    uses: sot/skare3/.github/workflows/package_build.yml@master
    with:
      noarch: false
    secrets:
      CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
      CHANDRA_XRAY_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
  upload:
    needs: [build]
    uses: sot/skare3/.github/workflows/package_upload.yml@master
    with:
      channel: test
  release:
    uses: sot/skare3/.github/workflows/package_release.yml@master
    secrets:
      SKARE3_CI_API_TOKEN: ${{ secrets.SKARE3_CI_API_TOKEN }}